---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: davidstone097@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # privateKeySecretRef:
    #   name: le-issuer-acct-key
    solvers:
    - dns01:
        cloudflare:
          email: davidstone097@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'osose.xyz'
        - '*.osose.xyz'


