configMap:
  name: bird-config
  bird_api_url: "http://birdimage:4200"

deployment:
  name: bird
  replicas: 1
  labels:
    app: bird
  container:
    name: bird
    image: "4568910/bird:v2"
    port: 4201
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 70

service:
  name: bird
  selector:
    app: bird
  port: 4201
  targetPort: 4201
  type: ClusterIP

ingress:
  name: "bird-ingress"
  host: "birdy.osose.xyz"
  